{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.fullnameOverride | default "nrf" }}-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fullnameOverride | default "nrf" }}
    network-function: nrf
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.fullnameOverride | default "nrf" }}
  endpoints:
    - port: metrics
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scheme: http
{{- end }}
