apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride | default "oc-nrf" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fullnameOverride | default "oc-nrf" }}
    network-function: nrf
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: {{ .Values.fullnameOverride | default "oc-nrf" }}
