apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride | default "scp" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fullnameOverride | default "scp" }}
    network-function: scp
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: {{ .Values.fullnameOverride | default "scp" }}
